### ISSUE TITLE
Cannot install in Moodle

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-arithmetic-quiz#4]
Hello,

I Downloaded  the zip h5p-arithmetic-quiz-master.zip from;

https://github.com/h5p/h5p-arithmetic-quiz

by pressing "clone or download" -> download as zip but when I try to upload it to the Moodle H5P-libraries I get an error;

Library directory name must match machineName or machineName-majorVersion.minorVersion (from library.json). (Directory: h5p-arithmetic-quiz-master , machineName: H5P.ArithmeticQuiz, majorVersion: 1, minorVersion: 0)

![h5perror](https://cloud.githubusercontent.com/assets/15193418/22647502/8c1da692-ec7a-11e6-86b4-8f3d3de8613e.PNG)

Installation instructions can be found here;

https://h5p.org/moodle#downloadsingle

**Comment by fnoks** [comment]
Hi,

Github does not create a valid H5P-file, it only zips the code each time we create a tag. You have to download the content types from h5p.org. The arithmetic quiz is found here: https://h5p.org/arithmetic-quiz. Click the download button in the toolbar below the H5P.
